version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: carlos 
      POSTGRES_PASSWORD: carlos123
      POSTGRES_DB: nestdb
    ports:
    - 5499:5432